server:
  port: 8082

spring:
  application:
    name: user-service
  profiles:
    active: local

  config:
    import: "optional:configserver:"

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
